FROM kubespheredev/builder-base:v3.1.0-podman

ARG JDK_VERSION 17.0.13
ARG JDK_HOME /usr/lib/jvm/java-${JDK_VERSION}-openjdk

# 定义构建参数
ARG BUILD_ENV=production
ENV RUNTIME_ENV=${BUILD_ENV}

# 打印所有信息
RUN echo "=== 调试信息 ===" && \
    echo "构建参数 BUILD_ENV: ${BUILD_ENV}" && \
    echo "运行时环境 RUNTIME_ENV: ${RUNTIME_ENV}" && \
    echo "当前用户: $(whoami)" && \
    echo "当前JAVA版本: $(JDK_VERSION)" && \
    echo "当前目录: $(pwd)"

# java
ENV JAVA_VERSION $JDK_VERSION

ARG ARCH="$(uname -m)"

RUN echo "=== 系统架构===" && \
    echo "ARCH: ${ARCH}"
