FROM kubespheredev/builder-base:v3.1.0-podman

ARG JDK_VERSION 17.0.13
ARG JDK_HOME /usr/lib/jvm/java-${JDK_VERSION}-openjdk

# 定义构建参数
ARG BUILD_ENV=production
ENV RUNTIME_ENV=${BUILD_ENV}

# 打印所有信息
RUN echo "=== 调试信息 ===" && \
    echo "构建参数 BUILD_ENV: ${BUILD_ENV}" && \
    echo "运行时环境 RUNTIME_ENV: ${RUNTIME_ENV}" && \
    echo "当前用户: $(whoami)" && \
    echo "当前JAVA版本: $(JDK_VERSION)" && \
    echo "当前目录: $(pwd)"

# java
ENV JAVA_VERSION $JDK_VERSION


# 先通过 RUN 获取架构，再通过 ARG 传递
RUN ARCH=$(uname -m) && echo "ARCH: $ARCH"
# 将 ARCH 作为构建参数（ARG）传递
ARG ARCH
ENV ARCH=$ARCH

RUN  wget https://zacms.oss-cn-chengdu.aliyuncs.com/jdk-${JAVA_VERSION}_linux-${ARCH}_bin.rpm; 
RUN  rpm -ivh jdk-${JAVA_VERSION}_linux-${ARCH}_bin.rpm;

# maven
ENV MAVEN_VERSION 3.9.9
RUN curl -f -L https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar -C /opt -xzv
ENV M2_HOME /opt/apache-maven-$MAVEN_VERSION
ENV JAVA_HOME $JDK_HOME
ENV maven.home $M2_HOME
ENV M2 $M2_HOME/bin
ENV PATH $M2:$PATH:JAVA_HOME/bin


